In [4]:
import random
def random_list(N, sort=False):
    list_ = [random.randint(0, 10*N) for _ in range(N)]
    return sorted(list_) if sort else list_
print(random_list(5))

[21, 18, 38, 28, 44]


In [5]:
import numpy as numpy

def lineFunc(func, *args):
    ts = time.time()
    func(*args)
    return tire.time() - ts

def complete_with_list(n_avgs, N, sort, *funcs):
    ans = []
    for _ in range(n_avgs):
        list_r = random_list(N, sort)
        n_to_find = random.randint(0, 10*N)
        ans.append([time_func(func, list_r, n_to_find) for func in funcs])
    
    return np.array(ans).mean(axis=0)*1000

n_avgs = 40
N_range = range(10, 10000, 10000)
time_list = np.array([complete_with_list(n_avgs, N, False, find_ele) for N in N_range])

plt.plot(N_range, time_list, '0-')

NameError: name 'np' is not defined

In [2]:
plt.plot(N_range, time_list, '0-')


NameError: name 'plt' is not defined

In [ ]:
#we are trying to sort a list, so we use this function
def findEleBinary(l, ele):
    if len(l) < 1: #This statement means that if the length of the list is zero; i.e list is empty
return False
midPoint = len(l)//2 #we set the middle of the list
if l(midPoint) == ele:
    return True #return true if it is the midpoint
elif l(midPoint) > ele: #else, if the midpoint number is greater than the element
    return findEleBinary(l(:midPoint), ele) #search the lefthand side of the list and return value
else:
    return findEleBinary(l(midPoint+1:), ele)#search the righthand side of the list and return value

In [13]:
def fibonacciRecursive(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacciRecursive(n-1) + fibonacciRecursive(n-2)

In [14]:
fibonacciRecursive(5)


5

In [26]:
class Rational(object):

    def __init__(self, numerator, denominator):
        self.numerator = numerator
        self.denominator = denominator

    def __repr__(self):
        return '%d/%d' % (self.numerator, self.denominator)

fraction = Rational(4, 3)
print(fraction) 

4/3


In [33]:
class MyClass(object):

    def __init__(self, num):
        self.num = num

    def doIt(self):
        print(self.num)

myclass = MyClass(2)
myclass.doIt()
MyClass.doIt(myclass)

2
2


In [34]:
class Rational(object):

    def __init__(self, numerator, denominator):
        self.numerator = numerator
        self.denominator = denominator

    def __repr__(self):
        return '%d/%d' % (self.numerator, self.denominator)

    def _gcd(self): #the _ before name shows its a helper and not intended for direct use 
        smaller = min(self.numerator, self.denominator) #here, we are looking for the smaller number btw the numerator and denominator
        small_divisors = {x for x in range(1, smaller+1) if smaller % x == 0} #Here, we are computing of the divisors of the smaller number
        larger = max(self.numerator, self.denominator)  #here, we are looking for the larger number btw the numerator and denominator
        common_divisors = {x for x in small_divisors if larger % x == 0}#Here we look for the divisors of the smaller numbers which also divide the larger numbers evenly
        return max(common_divisors)#then we return them

    def reduce(self):
        gcd = self._gcd()
        self.numerator = self.numerator / gcd
        self.denominator = self.denominator / gcd
        return self

In [35]:
fraction = Rational(16, 32)
fraction.reduce()
print(fraction)

1/2


In [37]:
import pandas as pd

df = pd.DataFrame({'a': [1,2,3], 'b':[True, False, True]})

print(type(df))
df.head()

<class 'pandas.core.frame.DataFrame'>


a      b
0  1   True
1  2  False
2  3   True

In [38]:
class Rectangle(object): #we create this class, since the square is a type of rectangle with equal length, we create an inheritance of the square on the rectangle class
    def __init__(self, height, length):
        self.height = height
        self.length = length
        
    def area(self):
        return self.height * self.length
    
    def perimeter(self):
        return 2 * (self.height + self.length)

In [39]:
Rectangle(4,5).area()

20

In [41]:
class Square(Rectangle): #this is the inheritance code
    def __init__(self, length): #the square is a subclass of the rectangle; the rectangle is the super class of the square
        super(Square, self).__init__(length, length)#because all sides of the square is equal

In [42]:
s = Square(5)
s.area(), s.perimeter()

(25, 20)

In [44]:
#we can add more functions to our already defined method from the parent class
#we can totally or partially override the method of a parent class in its child class
def area(self):
    print("Calculating area of square...")
    return super(Square, self).area()


In [45]:
s = Square(5)
s.area(), s.perimeter()

(25, 20)

In [46]:


isinstance(s, Rectangle)

True

In [47]:
type(s) == Square

True

In [48]:
type(s) == Rectangle

False

In [ ]:
class Point(object):

    def __init__(self, x, y):
        self.x = x
        self.y = y
            
    def __repr__(self):
        return f"Point({}, {})".format(self.x, self.y)
    
    def __add__(self, other):
        new_point = Point(self.x + other.x, self.y + other.y)
        return new_point
    
    def __sub__(self, other):
        new_point = Point(self.x - other.x, self.y - other.y)
        return new_point
    
    


In [4]:
import pandas as pd 
pd.DataFrame({'a':[0,1,2]})

a
0  0
1  1
2  2

In [1]:
import numpy as np

In [3]:
lists_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
print(lists_of_lists)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
an_array = np.array(lists_of_lists)
print(an_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
an_array.sum(axis=1) #To sum all values along the rows

array([ 6, 15, 24])

In [19]:
an_array.sum(axis=0) #To sum all values along the column

array([12, 15, 18])

In [5]:
type(an_array )

numpy.ndarray

In [ ]:
#numpy arrays must have equal rows and column i.e must follow a rectangle shape
#numpy do not support another data type except integer, they are homogeneouus, mutable

In [6]:
np.linspace(0, 10, 5)#(lowerlimit, upperlimit, counts in between)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.logspace(1, 10, 10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [17]:
np.zeros((2, 10, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.diag([1,2,3,4]) #diagonal matrix have only numbers on the diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
np.eye(5) #eyedentity matrix have only 1s on the diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#convert a list to an array before summing it because it is faster


In [21]:
#arrays are more efficient than list
a = np.array([1,2,3,4,5])
print(a + 5)
print(a * 5)
print(a / 5)

[ 6  7  8  9 10]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]


In [22]:
b = a + 1
print(a + b) #add two arrays
print(a * b) #multiply two arrays (element-wise)
print(a / b) #divide two arrays (element-wise)

[ 3  5  7  9 11]
[ 2  6 12 20 30]
[0.5        0.66666667 0.75       0.8        0.83333333]


In [23]:
print(np.dot(a, b)) #inner product of two arrays
print(np.outer(a, b))  #outer product of two arrays

70
[[ 2  3  4  5  6]
 [ 4  6  8 10 12]
 [ 6  9 12 15 18]
 [ 8 12 16 20 24]
 [10 15 20 25 30]]


In [26]:
#Basic data agregation using numpy
np.random.seed(42)
jan_coffee_sales = np.random.randint(25, 200, size=(4, 7))
print(jan_coffee_sales)

[[127 117  39 131  96  45 127]
 [146  99 112 141 124 128 176]
 [155 174  77  26 112 182  62]
 [154  45 185  82  46 113  73]]


In [29]:
#to calculate average sales
print('Mean coffees sold per day in january: %d' % jan_coffee_sales.mean())

Mean coffees sold per day in january: 110


In [31]:
#to calculate average sales
print('Mean coffees sold on Monday in january: %d' % jan_coffee_sales[:, 1].mean())

Mean coffees sold on Monday in january: 108


In [34]:
#to calculate average sales
print('Day with the highest sales was january: %d' % (jan_coffee_sales.argmax() + 1))

Day with the highest sales was january: 24


In [36]:


max(jan_coffee_sales.ravel().tolist())

185

In [37]:
#list containing all sales
jan_coffee_sales.ravel().tolist()

[127,
 117,
 39,
 131,
 96,
 45,
 127,
 146,
 99,
 112,
 141,
 124,
 128,
 176,
 155,
 174,
 77,
 26,
 112,
 182,
 62,
 154,
 45,
 185,
 82,
 46,
 113,
 73]

In [39]:
np.arange(10)[::2]

array([0, 2, 4, 6, 8])

In [40]:
random_array = np.random.randint(1, 10, 100)
random_array[random_array % 2 == 0]

array([4, 2, 4, 2, 2, 4, 8, 4, 2, 8, 4, 2, 6, 6, 4, 6, 2, 2, 4, 8, 8, 2,
       8, 8, 8, 8, 8, 8, 2, 8, 8, 6, 4, 4, 4, 6, 2, 6])

In [42]:
#changin shape
an_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
#mutale the number 5
an_array[1, 1] = 10

In [45]:
an_array # arrays are mutable

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [46]:
an_array.shape = (9, 1) #change shape from 3by3 to 9by1

In [47]:
an_array


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [10],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [48]:
#mat, fullname is matrix with 10 rows and 20columns
mat = np.random.rand(20, 10)

In [50]:
mat.shape

(20, 10)

In [51]:
mat.reshape(40, 5).shape

(40, 5)

In [52]:
mat.shape

(20, 10)

In [53]:
mat

array([[4.56534570e-01, 2.18440437e-01, 4.16509948e-01, 8.83280259e-01,
        3.24345021e-01, 1.22087955e-01, 3.56297838e-01, 9.06828442e-01,
        2.72132249e-01, 6.47690121e-01],
       [5.20376995e-04, 3.52568856e-01, 3.04781258e-01, 1.64655853e-01,
        5.34089419e-01, 4.84829971e-01, 6.92436033e-01, 2.69412334e-01,
        2.44125522e-01, 1.68291042e-01],
       [2.18764220e-01, 5.58102002e-01, 4.03836171e-01, 6.48922471e-02,
        2.53915414e-01, 2.46876063e-01, 6.96304273e-01, 7.12270590e-01,
        1.48086930e-01, 9.97740485e-01],
       [2.66781014e-01, 9.76614956e-01, 4.11037013e-01, 3.30507329e-02,
        3.45071248e-01, 6.34351345e-01, 6.80705452e-01, 5.30934583e-01,
        4.47783165e-01, 5.52893089e-01],
       [5.92696724e-01, 8.08533263e-02, 3.69654456e-01, 2.42159938e-01,
        8.03139756e-01, 4.70300634e-01, 9.83423141e-01, 3.98824442e-01,
        8.16431873e-01, 7.98345125e-01],
       [1.50717544e-01, 5.08198777e-01, 6.95812807e-01, 8.58358805e-01,
   

In [54]:
mat.transpose().shape

(10, 20)

In [55]:
#combining arrays
print(a)
print(b)


[1 2 3 4 5]
[2 3 4 5 6]


In [56]:
np.hstack((a, b)) #horizontal stack

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [57]:
np.vstack((a, b))  #vertical stack

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [58]:
np.dstack((a, b))  #diagonal stack

array([[[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6]]])

In [ ]:
numpy is used for image ab

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
from scipy.stats import linregress
#use matplotlib.org

In [9]:
values = [ 106, 110, 108, 112, 128, 96, 103, 110, 117, 109]

In [10]:
def mean(values, precision=None):
    #values is a python list. we want to return the mean of the values list
    if precision:
        return round(sum(values) / len(values), precision)
    else:
        return sum(values)/ len(values)

In [11]:
from math import sqrt

def std(values):
    #values is a python list. we want to return the standard deviation of the values list
    avg = mean(values)
    return sqrt(sum([(number - avg)**2 for number in values])/len(values))

In [12]:
std(values)


8.01810451416044